tmux:
  symbols:
    branch: ""
    hashprefix: ":"
    ahead: "↑"
    behind: "↓"
    staged: "✚"
    conflict: "✖"
    modified: "●"
    untracked: "…"
    stashed: "⚑"
    clean: ""
  styles:
    clear: "#[fg=#{@thm_blue},bg=#{@thm_surface_0}]"
    state: "#[fg=#{@thm_peach},bg=#{@thm_surface_0}]"
    branch: "#[fg=#{@thm_blue},bg=#{@thm_surface_0}]"
    remote: "#[fg=#{@thm_overlay_1},bg=#{@thm_surface_0}]"
    divergence: "#[fg=#{@thm_overlay_1},bg=#{@thm_surface_0}]"
    staged: "#[fg=#{@thm_green},bg=#{@thm_surface_0}]"
    conflict: "#[fg=#{@thm_red},bg=#{@thm_surface_0}]"
    modified: "#[fg=#{@thm_yellow},bg=#{@thm_surface_0}]"
    untracked: "#[fg=#{@thm_overlay_1},bg=#{@thm_surface_0}]"
    stashed: "#[fg=#{@thm_mauve},bg=#{@thm_surface_0}]"
    clean: "#[fg=#{@thm_green},bg=#{@thm_surface_0}]"
  layout: [branch, divergence, flags]
  options:
    branch_max_len: 24
