unbind C-b
set -g prefix C-Space
bind C-Space send-prefix
set -g focus-events on

set -g status-position top
set -g base-index 1
setw -g pane-base-index 1
set -g mouse on
set -g default-terminal "tmux-256color"
set -g status-interval 5
set -g automatic-rename off
set -g status-justify 'absolute-centre'

bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"

bind t display-popup -E "tmux new-session -A -s popup"

set -g @catppuccin_flavor 'macchiato'
set -g @catppuccin_status_background 'none'

# Window center
set -g @catppuccin_window_status_style "basic"
set -g @catppuccin_window_current_text_color "#{@thm_surface_0}"
set -g @catppuccin_window_current_number_color "#{@thm_flamingo}"
set -g @catppuccin_window_number_color "#{@thm_overlay_2}"
set -g @catppuccin_window_flags_icon_last ""
set -g @catppuccin_window_flags "icon"
set -g @catppuccin_window_flags_icon_current ""
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

# Session
set -g @catppuccin_session_icon "󱔁  "
set -g @catppuccin_session_color "#{@thm_peach}"
set -g @catppuccin_session_text " #{session_index} #S"

# Separators
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"

#pane zoom icon
set -g @catppuccin_window_flags_icon_zoom "  " 

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# ── Left Status ───────────────────────────────────────────────────
set -g status-left-length 100
set -g status-left ""
set -ga status-left "#{?client_prefix,#{#[bg=#{@thm_red},fg=#{@thm_mantle},bold] 󰇐  #{b:pane_current_path} },#{#[bg=#{@thm_lavender},fg=#{@thm_bg}] 󰇐  #{b:pane_current_path} }}"
set -ga status-left "#[bg=#{@thm_base},fg=#{@thm_lavender}]"

# ── Right Status ──────────────────────────────────────────────────
set -g status-right-length 100
set -g status-right ""
set -ga status-right "#[bg=#{@thm_bg},fg=#{@thm_blue}]█"
set -ga status-right "#[bg=#{@thm_blue},fg=#{@thm_mantle},bold] "
set -ga status-right "#[bg=#{@thm_surface_0},fg=#{@thm_blue}] #(gitmux -cfg ~/.config/tmux/gitmux.conf '#{pane_current_path}')  "
set -ga status-right "#{E:@catppuccin_status_session}"
